baseurl = "http://algoogle.hadrori.jp"
title = "Algoogle"
description = "Algorithm for Programming Contest"
disqusShortname = "Algoogle"

[taxonomies]
  category = "category"
  tag      = "tags"

[params]
  author = "hadrori"
  languageCode = "ja"
  countryCode = "ja"
  [params.socialtwitter]
    twitter = "hadrori"
